#pragma kernel Blend
#include "\Includes\Density.compute"

StructuredBuffer<float4> pointsA;
StructuredBuffer<float4> pointsB;
float weight;

[numthreads(numThreads, numThreads, numThreads)]
void Blend(int3 id : SV_DispatchThreadID) {
    if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis) {
        return;
    }
    
    int index = indexFromCoord(id.x, id.y, id.z);
    float densityA = pointsA[index].w;
    float densityB = pointsB[index].w;
    float blended = lerp(densityA, densityA * densityB, weight);
    
    points[index] = float4(pointsA[index].xyz, blended);
}