#pragma kernel Density
#include "\Includes\Density.compute"
#include "\Includes\Noise.compute"

StructuredBuffer<float3> offsets;
int octaves;
float lacunarity;
float persistence;
float noiseScale;
float caveScale;
float caveThreshold; // Controls cave size
float floorLevel;  // Y-level where caves start

[numthreads(numThreads, numThreads, numThreads)]
void Density(int3 id : SV_DispatchThreadID)
{
   if (id.x >= numPointsPerAxis || id.y >= numPointsPerAxis || id.z >= numPointsPerAxis) {
       return;
   }

   float3 vertPos = float3(id) * (boundsSize / (numPointsPerAxis - 1)) - boundsSize/2;
   float3 pos = centre + id * spacing - boundsSize / 2;
   float noise = 0;
   float frequency = noiseScale / 100;
   float amplitude = 1;

   for (int j = 0; j < octaves; j++) {
       float n = abs(snoise(pos * frequency + offsets[j]));
       noise += n * amplitude;
       amplitude *= persistence;
       frequency *= lacunarity;
   }
   
   float caveNoise = abs(snoise(pos * caveScale));
   float caves = caveNoise < caveThreshold ? -1 : 1;
   float heightMask = pos.y < floorLevel ? 1 : 0;
   
   float finalVal = caves * heightMask;
   int index = indexFromCoord(id.x, id.y, id.z);
   points[index] = float4(vertPos, finalVal);
}